import esbuild from "esbuild";
import process from "process";
import path from "path";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"use strict";
try {`;

// Surface fatal load errors on mobile, where the console is unreachable:
// show a persistent Notice and write the stack to a vault file.
const footer = `} catch (__loadError) {
  try {
    // JavaScriptCore's error.stack omits the message, so include both explicitly.
    var __msg = "LLM Hub failed to load: " + String(__loadError) + "\\n" + ((__loadError && __loadError.stack) || "");
    try { new (require("obsidian").Notice)(__msg, 0); } catch (_) {}
    try {
      var __app = (typeof window !== "undefined" && window.app) || (typeof globalThis !== "undefined" && globalThis.app);
      if (__app && __app.vault && __app.vault.adapter) { __app.vault.adapter.write("llm-hub-load-error.log", __msg); }
    } catch (_) {}
  } catch (_) {}
  throw __loadError;
}`;

const prod = process.argv.includes("production");
const langfuseBuild = process.argv.includes("langfuse");

// Patch langfuse-core for Obsidian compatibility.
// langfuse-core uses dynamic import("fs")/import("crypto") to detect Node.js,
// but Electron's renderer resolves import() via Chromium's ESM loader which
// cannot find Node builtins. Skip the Node/Deno branches and use Web Crypto API
// (available in Electron and mobile WebView) instead.
const langfuseCompatPlugin = {
  name: "langfuse-compat",
  setup(build) {
    build.onLoad({ filter: /langfuse-core[\\/]lib[\\/]index\.(cjs\.js|mjs)$/ }, async (args) => {
      let contents = fs.readFileSync(args.path, "utf8");

      const target = [
        `const dynamicImport = module => {`,
        `  return import( /* webpackIgnore: true */module);`,
        `};`,
        `if (typeof globalThis.Deno !== "undefined") {`,
        `  // Deno`,
        `  Promise.all([dynamicImport("node:fs"), dynamicImport("node:crypto")]).then(([importedFs, importedCrypto]) => {`,
        `    fs = importedFs;`,
        `    cryptoModule = importedCrypto;`,
        `  }).catch(); // Errors are handled on runtime`,
        `} else if (typeof process !== "undefined" && process.versions?.node) {`,
        `  // Node`,
        `  Promise.all([dynamicImport("fs"), dynamicImport("crypto")]).then(([importedFs, importedCrypto]) => {`,
        `    fs = importedFs;`,
        `    cryptoModule = importedCrypto;`,
        `  }).catch(); // Errors are handled on runtime`,
        `} else if (typeof crypto !== "undefined") {`,
        `  // Edge runtime (Cloudflare Workers, Vercel Cloud Function)`,
        `  cryptoModule = crypto;`,
        `}`,
      ].join("\n");

      const replacement = [
        `// [patched for Obsidian] Use Web Crypto API instead of dynamic import("fs")/import("crypto")`,
        `if (typeof crypto !== "undefined") {`,
        `  cryptoModule = crypto;`,
        `}`,
      ].join("\n");

      if (contents.includes(target)) {
        contents = contents.replace(target, replacement);
      } else {
        console.warn("langfuse-compat: expected code block not found in " + args.path);
        console.warn("langfuse-core may have been updated — check for dynamic import('fs') compatibility.");
      }

      return { contents, loader: args.path.endsWith(".mjs") ? "js" : "js" };
    });
  },
};

// When langfuse is not included, redirect all imports of langfuse module to noop stub.
// This eliminates the entire langfuse implementation and SDK from the bundle.
const langfuseNoopPlugin = {
  name: "langfuse-noop",
  setup(build) {
    // Match any import that resolves to src/tracing/langfuse.ts (but not langfuse-noop.ts)
    build.onResolve({ filter: /langfuse/ }, (args) => {
      // Skip the langfuse npm package import (only in langfuse.ts itself)
      if (args.path === "langfuse") return undefined;
      // Skip the noop file itself
      if (args.path.includes("langfuse-noop")) return undefined;
      // Redirect src/tracing/langfuse → langfuse-noop.ts
      if (args.path.endsWith("/langfuse") || args.path === "src/tracing/langfuse") {
        return { path: path.resolve("src/tracing/langfuse-noop.ts") };
      }
      return undefined;
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  footer: {
    js: footer,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  platform: "node",
  inject: ["./process-shim.js"],
  alias: {
    "debug": "./debug-stub.js",
    // Use browser version of @google/genai for mobile compatibility
    "@google/genai": "@google/genai/web",
    // Use browser version of fflate: the node build pulls in
    // require("module").createRequire / worker_threads, which crashes
    // Obsidian mobile at plugin load (no Node builtins in the WebView)
    "fflate": "fflate/browser",
  },
  define: {
    "process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
    "global": "globalThis",
  },
  external: [
    "obsidian",
    "electron",
    "child_process",
    "node-pty",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  jsxFactory: "React.createElement",
  jsxFragment: "React.Fragment",
  plugins: langfuseBuild ? [langfuseCompatPlugin] : [langfuseNoopPlugin],
  loader: {
    ".ts": "ts",
    ".tsx": "tsx",
    ".css": "css",
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
